name: SoulSecurity
main: com.strixmc.souls.Security
version: 1.1.0-BETA.3
author: Sliide_
softdepend:
  - AuthMe

permissions:
  souls.admin:
    default: false
  soul.command.setpin:
    default: op
  soul.command.pin:
    default: op
